apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  labels:
    app: {{ include "api.name" . }}
  namespace: {{ .Values.namespace.api.name }}
data:
  SERVER_ADDRESS: {{ .Values.api.server.address | quote }}
  SERVER_PORT: {{ .Values.api.server.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.api.server.profilesActive | quote }}
  OTEL_GRPC_ENDPOINT: {{ .Values.api.otel.grpcEndpoint | quote }}
