namespace:
  api:
    name: replaced
  monitor:
    name: replaced
    
api:
  name: worker

  replicaCount: 2

  image:
    repository: "replaced"
    tag: "replaced"

  ports:
    port: 9090
    name: http

  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

  probe:
    path:
      startup: /actuator/health
      liveness: /actuator/health/liveness
      readiness: /actuator/health/readiness

  server:
    address: 0.0.0.0
    port: 9090
    profilesActive: "prod"

  hpa:
    minReplicas: 1
    maxReplicas: 2
  
  keda:
    serviceBus:
      queueName: "replaced"
      namespace: "replaced"
      messageCount: 5
      
secrets:
  azureKeyVault:
    keyVaultName: "replaced"
    tenantId: "replaced"
    clientID: "replaced"