name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  TF_VAR_videocore-backend-resource-group: ${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}
  TF_VAR_videocore-backend-storage-account: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}
  TF_VAR_videocore-backend-container: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}
  TF_VAR_videocore-backend-infra-key: ${{secrets.VIDEOCORE_INFRA_BACKEND_AZURE_KEY}}

  TF_VAR_chart_name: "videocore-worker"
  TF_VAR_chart_version: "0.1.${{ github.run_number }}"
  TF_VAR_docker_image_tag: "${{ github.run_number }}"

jobs:
  infra-info:
    runs-on: ubuntu-latest
    env:
      TF_VAR_docker_image_uri: "default"
    outputs:
      acr_login_server: ${{ steps.acr.outputs.acr_login_server }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      # Somente para que o output seja criado
      - name: Terraform Apply Refresh Only
        working-directory: terraform
        run: terraform apply --refresh-only --auto-approve

      - name: Get ACR Login Server from remote state
        id: acr
        working-directory: terraform
        run: echo "acr_login_server=$(terraform output -raw acr_login_server_from_remote)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: infra-info
    defaults:
      run:
        working-directory: worker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: "25"
          distribution: "temurin"
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Unit Test with Gradle (finalizedBy JacocoTestReport)
        run: ./gradlew test --no-daemon

      - name: Build and analyze with SonarCloud
        run: ./gradlew sonar "-Dsonar.qualitygate.wait=true" --no-daemon --info
        env:
          SONAR_CLOUD_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}

  push:
    needs: [build, infra-info]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ needs.infra-info.outputs.acr_login_server }}

      - name: Helm Login to ACR
        run: |
          az account set --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
          
          ACR_LOGIN_SERVER=${{ needs.infra-info.outputs.acr_login_server }}
          ACR_USERNAME=$(az acr credential show --name ${ACR_LOGIN_SERVER} --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name ${ACR_LOGIN_SERVER} --query "passwords[0].value" -o tsv)
          echo $ACR_PASSWORD | helm registry login $ACR_LOGIN_SERVER --username $ACR_USERNAME --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ needs.infra-info.outputs.acr_login_server }}/videocore-worker:${{ github.run_number }}
          docker build -t $IMAGE_NAME -f docker/Dockerfile .
          docker push $IMAGE_NAME

      - name: Build and Push Package Helm Chart
        run: |
          CHART_VERSION="0.1.${{ github.run_number }}"
          sed -i "s/^version:.*/version: $CHART_VERSION/" kubernetes/videocore-worker/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: $CHART_VERSION/" kubernetes/videocore-worker/Chart.yaml
          helm dependency update kubernetes/videocore-worker
          helm package kubernetes/videocore-worker -d ./charts
          ACR_NAME=${{ needs.infra-info.outputs.acr_login_server }}
          helm push ./charts/videocore-worker-*.tgz oci://$ACR_NAME/helm

  terraform:
    runs-on: ubuntu-latest
    needs: [push, infra-info]
    env:
      TF_VAR_docker_image_uri: "${{ needs.infra-info.outputs.acr_login_server }}/videocore-worker"

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan